pub const GENERATED_HEADER: &str = "Generated by LocalLabStack. Manual edits may be overwritten.";
pub const BEGIN_HOSTS_MARKER: &str = "# BEGIN LocalLabStack";
pub const END_HOSTS_MARKER: &str = "# END LocalLabStack";
