use std::fs;
use std::path::Path;

use anyhow::{Context, Result, bail};

use crate::config::GENERATED_HEADER;
use crate::manifest::{AppManifest, RootManifest};

#[derive(Clone, Debug, PartialEq, Eq)]
pub struct Route {
    pub app_name: String,
    pub domain: String,
    pub container: String,
    pub port: u16,
}

pub fn collect_routes(apps: &[AppManifest]) -> Result<Vec<Route>> {
    let mut routes = Vec::new();
    for app in apps {
        let public = app.public_upstreams();
        if public.len() > 1 {
            bail!(
                "app {} has multiple public upstreams; this is not supported yet",
                app.name
            );
        }
        if let Some((_, upstream)) = public.first() {
            routes.push(Route {
                app_name: app.name.clone(),
                domain: app.domain.clone(),
                container: upstream.container.clone(),
                port: upstream.port,
            });
        }
    }
    routes.sort_by(|left, right| left.app_name.cmp(&right.app_name));
    Ok(routes)
}

pub fn render_caddyfile(_root: &RootManifest, routes: &[Route]) -> String {
    let mut output = format!("# {GENERATED_HEADER}\n\n{{\n  auto_https off\n}}\n\n");
    for route in routes {
        output.push_str(&format!(
            "{} {{\n  tls /certs/issued/locallab.pem /certs/issued/locallab-key.pem\n  reverse_proxy {}:{}\n}}\n\n",
            route.domain, route.container, route.port
        ));
    }
    output.push_str(
        "*.locallab {\n  tls /certs/issued/locallab.pem /certs/issued/locallab-key.pem\n  respond \"Unknown LocalLabStack app\" 404\n}\n",
    );
    output
}

pub fn write_caddyfile(path: &Path, content: &str, force: bool) -> Result<()> {
    if path.exists() {
        let existing = fs::read_to_string(path)
            .with_context(|| format!("failed to read {}", path.display()))?;
        if !existing.contains(GENERATED_HEADER) && !force {
            bail!(
                "{} does not look generated by LocalLabStack; use --force to overwrite",
                path.display()
            );
        }
    }
    fs::write(path, content).with_context(|| format!("failed to write {}", path.display()))
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::manifest::RootManifest;

    #[test]
    fn renders_fallback_without_routes() {
        let text = render_caddyfile(&RootManifest::default_named("default"), &[]);
        assert!(text.contains("*.locallab"));
    }
}
